### PR TITLE
Close connections after data is processed

### PR DESCRIPTION
**Pull request by knut-ytterhaug**
To avoid running out of FDs I suggest closing the connections after data is processed.

This might have a side effect of reduced memory consumption as well.

### CODE REVIEW

**Comment by mdiazv** [comment]
I'm running into the FD problem and knutemann's code does fix it.

**Comment by mdiazv** [comment]
Awesome speed! Thank you!
Is it likely that there would be a new docker image available?

**Comment by blaubaer** [comment]
@mdiazv Yes. Done. I've also make the whole build process right now automated and added schematic version numbers also for the docker images. Have fun! :)

**Comment by mdiazv** [comment]
\m/ you rock!

**Pull request merged**
